добавил новые методы
v8platform/mdclasses pull request #5
Opened 2021-05-03 08:11 UTC by thedemoncat

2021-05-03 08:11 UTC, thedemoncat commented
@khorevaa Посмотри, что скажешь?

2021-05-03 09:33 UTC, khorevaa requested changes

2021-05-03 09:33 UTC, khorevaa commented on mdoTypes.go
> +func (e MDOTypeRefList) Exist(typeRef *MDOTypeRef) bool {
Вот тут надо использовать не указатель.... или хотябы проверить указатель на nil

2021-05-03 09:33 UTC, khorevaa commented on mdoTypes.go
> +		if typeRef.raw != "" && t.raw == typeRef.raw {
Думаю правильная проверка сначала сравнение типов,  потом уже ссылок...  да и вообще ее можно сделать через getIndex, если он больше -1 тогда и элемент существует.. ну и ошибку проверить..

2021-05-03 09:35 UTC, khorevaa commented on mdoTypes.go
> +func RemoveElement(list []MDOTypeRef, i int) []MDOTypeRef {
Сделай метод приватным! Не нужен от публичным т.к он вызывается в `MDOTypeRefList.Delete`

2021-05-03 09:37 UTC, khorevaa commented on mdoTypes.go
> +		if typeRef.raw != "" && t.raw == typeRef.raw {
Кстати а вообще он зачем? )) Может достаточно GetIndex? Или метода Get?

2021-05-03 11:01 UTC, thedemoncat commented on mdoTypes.go
> +		if typeRef.raw != "" && t.raw == typeRef.raw {
хочу возврат булево.

2021-05-03 11:02 UTC, thedemoncat commented on mdoTypes.go
> +func RemoveElement(list []MDOTypeRef, i int) []MDOTypeRef {
готово

2021-05-03 11:15 UTC, khorevaa requested changes

2021-05-03 11:15 UTC, khorevaa commented on mdoTypes.go
> +		return e.GetIndex(typeRef.raw) > -1
А почему ты индекс получаешь по строке?  Индекс надо получать также по типу+ссылке!
В raw может что-то быть или нет

2021-05-03 11:36 UTC, khorevaa commented on mdoTypes.go
> +		return e.GetIndex(typeRef.raw) > -1
Ну в целом можно просто вызвать typeRef.String()  и сравнивать их

2021-05-10 05:46 UTC, thedemoncat commented on mdoTypes.go
> +		return e.GetIndex(typeRef.raw) > -1
Исправил

2021-05-13 13:20 UTC, merged